#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# stop & uninstall virtualbox
# il faudra surement gerer l'extinction des machines allumé par la suite

sudo service vboxweb_ynh stop
sudo rm /lib/systemd/system/vboxweb_ynh.service
sudo rm /etc/default/virtualbox 
sudo apt-get purge virtualbox-$VBOX_VERSION

# Remove webapps
sudo rm -rf /var/www/$app

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
# Reload nginx service
sudo service php5-fpm reolad
sudo service nginx reload
